source 'https://rubygems.org'

gem 'awesome_print'
gem 'byebug'
gem 'concurrent-ruby', require: 'concurrent'
gem 'concurrent-ruby-ext'
gem 'contracts'
gem 'hirb'
gem 'pry'
gem 'pry-byebug'
gem 'railroady'
gem 'rspec'
gem 'rubocop'
gem 'rubocop-performance'
gem 'rubocop-rspec'
gem 'table_print'
gem 'yard'
gem 'yard-contracts'


